spring.application.name=Oauth2



#spring.security.user.name=user
#spring.security.user.password=password


spring.security.oauth2.client.registration.google.client-id=560660532789-2750m14i1cihuls196ot8vbr6nadan6h.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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


spring.datasource.url=jdbc:mysql://localhost:3306/SampleDatabase
spring.datasource.username=root
spring.datasource.password=Purnima@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=info

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=purnimasahoo235@gmail.com
spring.mail.password=eyvr iead ktvx uuqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

zeebe.client.broker.gateway-address=http://127.0.0.1:26500
zeebe.client.security.plaintext=true


camunda.client.auth.method=basic
camunda.client.auth.username=demo
camunda.client.auth.password=demo
camunda.client.enabled=true
camunda.client.mode=selfManaged



