server:
  port: 9999
  servlet:
    session:
      cookie:
        name: SERVERCOOKIE
spring:
  web:
    resources:
      static-locations: file:uploads/, classpath:/static/
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/spring?useSSL=true
    password: realtiger
  application:
    base-url: http://localhost:9999/

logging:
  level:
    com.pns.oauthserver: trace